<a href="https://colab.research.google.com/github/hkbu-kennycheng/comp3925/blob/main/lab2_essential_python_module_for_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Essential Python module for data analytics

---

## Requests module and file IO

In [ ]:
!pip install requests

In [ ]:
import requests

r = requests.get('https://www.hktvmall.com/hktv/zh/ajax/getPromotedTop10?zone=supermarket&pageSize=10&currentPage=0')
data = r.json()

print(data)

{'image': {'imageType': None, 'format': None, 'url': '//images.hktvmall.com/banner/bannerzh_220104050139.jpg', 'altText': 'cny2022_jan_wbd_sm_top10', 'galleryIndex': None, 'width': None, 'hoverImageUrl': None}, 'url': '/hktv/zh/search?q=::category:BB01000087441:categoryHotPickOrder:BB01000087441:street:main', 'pagination': {'pageSize': 10, 'currentPage': 0, 'sort': None, 'numberOfPages': 182, 'totalNumberOfResults': 1813}, 'products': [{'code': 'H5938001_S_NYC-GB-202001', 'name': '燕窩鮑魚新年賀歲福袋 | 賀年禮盒 | 送禮', 'url': 'main/Lo-Hong-Ka/s/H5938001/%E8%AD%B7%E7%90%86%E4%BF%9D%E5%81%A5/%E8%AD%B7%E7%90%86%E4%BF%9D%E5%81%A5/%E4%BF%9D%E5%81%A5%E7%94%A2%E5%93%81/%E9%9B%9E%E7%B2%BE-%E7%87%95%E7%AA%A9/%E7%87%95%E7%AA%A9%E9%AE%91%E9%AD%9A%E6%96%B0%E5%B9%B4%E8%B3%80%E6%AD%B2%E7%A6%8F%E8%A2%8B-%E8%B3%80%E5%B9%B4%E7%A6%AE%E7%9B%92-%E9%80%81%E7%A6%AE/p/H5938001_S_NYC-GB-202001', 'description': '<h4><strong>極品冰糖官燕禮盒 – 6支裝 – 老行家即食燕窩 x1盒</strong></h4><p><strong>極品冰糖官燕以罕見矜貴的頭期官燕精燉而成</strong><strong> – </strong

In [ ]:
print(data['products'])

[{'code': 'H5938001_S_NYC-GB-202001', 'name': '燕窩鮑魚新年賀歲福袋 | 賀年禮盒 | 送禮', 'url': 'main/Lo-Hong-Ka/s/H5938001/%E8%AD%B7%E7%90%86%E4%BF%9D%E5%81%A5/%E8%AD%B7%E7%90%86%E4%BF%9D%E5%81%A5/%E4%BF%9D%E5%81%A5%E7%94%A2%E5%93%81/%E9%9B%9E%E7%B2%BE-%E7%87%95%E7%AA%A9/%E7%87%95%E7%AA%A9%E9%AE%91%E9%AD%9A%E6%96%B0%E5%B9%B4%E8%B3%80%E6%AD%B2%E7%A6%8F%E8%A2%8B-%E8%B3%80%E5%B9%B4%E7%A6%AE%E7%9B%92-%E9%80%81%E7%A6%AE/p/H5938001_S_NYC-GB-202001', 'description': '<h4><strong>極品冰糖官燕禮盒 – 6支裝 – 老行家即食燕窩 x1盒</strong></h4><p><strong>極品冰糖官燕以罕見矜貴的頭期官燕精燉而成</strong><strong> – </strong><strong>免浸、免揀、免燉。</strong></p><p></p><p>老行家極品冰糖官燕含豐富的水溶性蛋白質，能有效加強免疫力，更有滋陰調氣、補肺養陰之效。以罕見矜貴的頭期官燕精燉而成，營養成份比一般燕窩更高，味道清甜。選用先進高溫殺菌技術製作，真空處理，香港製造，並經由多種嚴格檢測，保證安全衛生。而且百分百天然，絕不添加防腐劑、人造色素或穩定劑，給每寸肌膚與身體更佳滋養，加倍呵護。</p><p>產地：香港，老行家自設廠房<br/>成份：頂級官燕、純水、冰糖<br/>營養：含豐富的水溶性蛋白質及多種微量元素<br/>功效：有效加強免疫力，更有滋陰調氣、補肺養陰之效<br/>口感：清甜可口<br/>用法：每日一樽，持續給每寸肌膚及身體充分滋養<br/>容量：70克 x 6樽<br/>保存方法：置於陰涼乾燥處，最佳保存期為18個月，避免陽光直接照射，開瓶後請馬上食用</p><p></p><p></p><h4><strong>精選原木花菇禮盒－八両裝 x1盒<

In [ ]:
print(data['products'][0]['name'])
print(data['products'][0]['averageRating'])
print(data['products'][0]['price']['value'])

燕窩鮑魚新年賀歲福袋 | 賀年禮盒 | 送禮
2.0
802.0


## Json module

JSON (JavaScript Object Notation) is a lightweight data-interchange format. It is easy for humans to read and write. It is easy for machines to parse and generate. It is based on a subset of the JavaScript Programming Language Standard.

We could store json data to a file.

In [ ]:
import json

json_file = open("products.json", "w")
json.dump(data['products'], json_file)
json_file.close()

And load json file into Python.

In [ ]:
json_file = open("products.json", "r")
data = json.load(json_file)
json_file.close()

print(data)

[{'code': 'H5938001_S_NYC-GB-202001', 'name': '燕窩鮑魚新年賀歲福袋 | 賀年禮盒 | 送禮', 'url': 'main/Lo-Hong-Ka/s/H5938001/%E8%AD%B7%E7%90%86%E4%BF%9D%E5%81%A5/%E8%AD%B7%E7%90%86%E4%BF%9D%E5%81%A5/%E4%BF%9D%E5%81%A5%E7%94%A2%E5%93%81/%E9%9B%9E%E7%B2%BE-%E7%87%95%E7%AA%A9/%E7%87%95%E7%AA%A9%E9%AE%91%E9%AD%9A%E6%96%B0%E5%B9%B4%E8%B3%80%E6%AD%B2%E7%A6%8F%E8%A2%8B-%E8%B3%80%E5%B9%B4%E7%A6%AE%E7%9B%92-%E9%80%81%E7%A6%AE/p/H5938001_S_NYC-GB-202001', 'description': '<h4><strong>極品冰糖官燕禮盒 – 6支裝 – 老行家即食燕窩 x1盒</strong></h4><p><strong>極品冰糖官燕以罕見矜貴的頭期官燕精燉而成</strong><strong> – </strong><strong>免浸、免揀、免燉。</strong></p><p></p><p>老行家極品冰糖官燕含豐富的水溶性蛋白質，能有效加強免疫力，更有滋陰調氣、補肺養陰之效。以罕見矜貴的頭期官燕精燉而成，營養成份比一般燕窩更高，味道清甜。選用先進高溫殺菌技術製作，真空處理，香港製造，並經由多種嚴格檢測，保證安全衛生。而且百分百天然，絕不添加防腐劑、人造色素或穩定劑，給每寸肌膚與身體更佳滋養，加倍呵護。</p><p>產地：香港，老行家自設廠房<br/>成份：頂級官燕、純水、冰糖<br/>營養：含豐富的水溶性蛋白質及多種微量元素<br/>功效：有效加強免疫力，更有滋陰調氣、補肺養陰之效<br/>口感：清甜可口<br/>用法：每日一樽，持續給每寸肌膚及身體充分滋養<br/>容量：70克 x 6樽<br/>保存方法：置於陰涼乾燥處，最佳保存期為18個月，避免陽光直接照射，開瓶後請馬上食用</p><p></p><p></p><h4><strong>精選原木花菇禮盒－八両裝 x1盒<

# External modules: numpy, pandas and seaborn

---

In [ ]:
!pip install numpy pandas seaborn 

# Numpy: The N-dimensional array container `ndarray`


Let's import `numpy` module as `np`

In [ ]:
import numpy as np

help(np.ndarray)

Help on class ndarray in module numpy:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |

https://numpy.org/doc/stable/reference/arrays.ndarray.html

`ndarray` is a multidimensional container of items same type and size.

## Revision and more: list, string and dict

In [ ]:
#@markdown ![](https://www.tensorflow.org/guide/images/tensor/strings.png)

strvector = ["Gray wolf", "Quick brown fox", "Lazy dog"]
print(strvector)
print('len:', len(strvector))

['Gray wolf', 'Quick brown fox', 'Lazy dog']
len: 3


In [ ]:
#@title Python list comprehension
#@markdown ![](https://url2img-web.herokuapp.com/aHR0cHM6Ly9kb2NzLnB5dGhvbi5vcmcvMy90dXRvcmlhbC9kYXRhc3RydWN0dXJlcy5odG1sI2xpc3QtY29tcHJlaGVuc2lvbnM=)

wordmatrix = [words.split(' ') for words in strvector]
print(wordmatrix)

[['Gray', 'wolf'], ['Quick', 'brown', 'fox'], ['Lazy', 'dog']]


In [ ]:
#@title Exercise: transform HKTVmall products into a list of dict format, name it as `products`.
#@markdown ```[{name:"product name", rating:2.0, price:802.0},...]```


[{'name': '燕窩鮑魚新年賀歲福袋 | 賀年禮盒 | 送禮', 'rating': 2.0, 'price': 802.0}, {'name': '朱古力及甜點禮盒32粒裝 #Ferrero #金莎 #費列羅', 'rating': 4.0, 'price': 155.0}, {'name': '福星報喜【小品蝴蝶蘭6棵】｜自家蘭花園種植 蘭花 蝴蝶蘭', 'rating': 4.1, 'price': 880.0}, {'name': '尚品虎虎生威鮑魚福袋(1套6款) - 鮑魚盛宴｜送禮自用首選', 'rating': 4.5, 'price': 679.0}, {'name': '風沙鹽焗雞 (約900克/隻 - 急凍熟食 - 翻熱即可食用)', 'rating': 4.3, 'price': 78.0}, {'name': 'KQB-29E 迷你韓式光波燒烤爐 香港行貨', 'rating': 4.9, 'price': 1399.0}, {'name': '西藏那曲冬蟲夏草(62-77條/盒)(18.5克/盒) #珍品大條 #送禮推介', 'rating': 4.5, 'price': 5680.0}, {'name': '皇牌Fango美膚泥漿入門套裝', 'rating': 4.1, 'price': 896.0}, {'name': '人體工學全網電腦椅辦公椅MR-A810 黑色', 'rating': 5.0, 'price': 2299.0}, {'name': '[即開即食] 尚品阿福鮑魚(四隻裝) x4罐', 'rating': 4.5, 'price': 472.0}]


## Converting values to numpy array with `np.array`

In [ ]:
scalar = np.array(4)
print(scalar, type(scalar))
print(scalar.dtype)

4 <class 'numpy.ndarray'>
int64


In [ ]:
vector = np.array([2.0, 3.0, 4.0])
print(vector, type(vector))
print(vector.dtype)

[2. 3. 4.] <class 'numpy.ndarray'>
float64


In [ ]:
matrix = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
print(matrix, type(matrix))

[[1 2]
 [3 4]
 [5 6]] <class 'numpy.ndarray'>


In [ ]:
dddarray = np.array([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],
])
print(dddarray, type(dddarray))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]] <class 'numpy.ndarray'>


In [ ]:
#@title Convert to ndarry from ragged sequence
#@markdown ![](https://www.tensorflow.org/guide/images/tensor/string-split.png)

wordmatrix1 = np.array(wordmatrix)
print(wordmatrix1, type(wordmatrix1))

print('values:\t', wordmatrix1)
print('dtype:\t', wordmatrix1.dtype)
print('ndim:\t', wordmatrix1.ndim)
print('shape:\t', wordmatrix1.shape)
print('size:\t', wordmatrix1.size)

[list(['Gray', 'wolf']) list(['Quick', 'brown', 'fox'])
 list(['Lazy', 'dog'])] <class 'numpy.ndarray'>
values:	 [list(['Gray', 'wolf']) list(['Quick', 'brown', 'fox'])
 list(['Lazy', 'dog'])]
dtype:	 object
ndim:	 1
shape:	 (3,)
size:	 3


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  after removing the cwd from sys.path.


In [ ]:
#@title convert `ndarray` back to list
dddarray.tolist()

[[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]],
 [[10, 11, 12, 13, 14], [15, 16, 17, 18, 19]],
 [[20, 21, 22, 23, 24], [25, 26, 27, 28, 29]]]

## `ndarray` properties

In [ ]:
#@title 0d array, also known as scalar
print('values:\t', scalar)
print('dtype:\t', scalar.dtype)
print('ndim:\t', scalar.ndim)
print('shape:\t', scalar.shape)
print('size:\t', scalar.size)

values:	 4
dtype:	 int64
ndim:	 0
shape:	 ()
size:	 1


In [ ]:
#@title 1d array, also known as vector
#@markdown ![](https://www.tensorflow.org/guide/images/tensor/vector.png)

print('values:\t', vector)
print('dtype:\t', vector.dtype)
print('ndim:\t', vector.ndim)
print('shape:\t', vector.shape)
print('size:\t', vector.size)

values:	 [2. 3. 4.]
dtype:	 float64
ndim:	 1
shape:	 (3,)
size:	 3


In [ ]:
#@title 2d array, also known as matrix
#@markdown ![](https://www.tensorflow.org/guide/images/tensor/matrix.png)

print('values:', matrix)
print('dtype:\t', matrix.dtype)
print('ndim:\t', matrix.ndim)
print('shape:\t', matrix.shape)
print('size:\t', matrix.size)

values: [[1 2]
 [3 4]
 [5 6]]
dtype:	 int64
ndim:	 2
shape:	 (3, 2)
size:	 6


In [ ]:
#@title 3d array
#@markdown ![](https://www.tensorflow.org/guide/images/tensor/3-axis_front.png)

print('values:', dddarray)
print('dtype:\t', dddarray.dtype)
print('ndim:\t', dddarray.ndim)
print('shape:\t', dddarray.shape)
print('size:\t', dddarray.size)

values: [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]
dtype:	 int64
ndim:	 3
shape:	 (3, 2, 5)
size:	 30


## Generating `ndarray`

In [ ]:
#@title Generating a 4d array with zeros
#@markdown ![](https://www.tensorflow.org/guide/images/tensor/4-axis_block.png)

ddddarray = np.zeros([3, 2, 4, 5])

print('values:', ddddarray)
print('dtype:\t', ddddarray.dtype)
print('ndim:\t', ddddarray.ndim)
print('shape:\t', ddddarray.shape)
print('size:\t', ddddarray.size)

values: [[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]]
dtype:	 float64
ndim:	 4
shape:	 (3, 2, 4, 5)
size:	 120


In [ ]:
#@markdown ![](https://www.tensorflow.org/guide/images/tensor/shape.png)

print(ddddarray.shape[0])
print(ddddarray.shape[-1])

3
5


In [ ]:
#@title `fill` array with values

ddddarray.fill(10)
print(ddddarray)

[[[[10. 10. 10. 10. 10.]
   [10. 10. 10. 10. 10.]
   [10. 10. 10. 10. 10.]
   [10. 10. 10. 10. 10.]]

  [[10. 10. 10. 10. 10.]
   [10. 10. 10. 10. 10.]
   [10. 10. 10. 10. 10.]
   [10. 10. 10. 10. 10.]]]


 [[[10. 10. 10. 10. 10.]
   [10. 10. 10. 10. 10.]
   [10. 10. 10. 10. 10.]
   [10. 10. 10. 10. 10.]]

  [[10. 10. 10. 10. 10.]
   [10. 10. 10. 10. 10.]
   [10. 10. 10. 10. 10.]
   [10. 10. 10. 10. 10.]]]


 [[[10. 10. 10. 10. 10.]
   [10. 10. 10. 10. 10.]
   [10. 10. 10. 10. 10.]
   [10. 10. 10. 10. 10.]]

  [[10. 10. 10. 10. 10.]
   [10. 10. 10. 10. 10.]
   [10. 10. 10. 10. 10.]
   [10. 10. 10. 10. 10.]]]]


In [ ]:
#@title Generating a 4d array with ones
ddddarray = np.ones([3, 2, 4, 5])
print(ddddarray)

[[[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]]


In [ ]:
#@title Generating a matrix with eye
matrix1 = np.eye(3, 3)
print(matrix1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#
matrix1 = np.eye(3, 3, 1)
print(matrix1)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [ ]:
matrix1 = np.eye(3, 3, -1)
print(matrix1)

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [ ]:
strmatrix = np.full([3, 2], 'hello')
print(strmatrix)

[['hello' 'hello']
 ['hello' 'hello']
 ['hello' 'hello']]


In [ ]:
np.random.randn(5)

array([-0.71847498,  0.13142583, -0.41193851,  0.0626571 ,  0.66964219])

## Shape manipulation


In [ ]:
#@title Matrix transpose
#@markdown ![](https://upload.wikimedia.org/wikipedia/commons/e/e4/Matrix_transpose.gif)

print(matrix)
print(matrix.T)
print(matrix.T.T == matrix)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]
[[ True  True]
 [ True  True]
 [ True  True]]


In [ ]:
# Example of transpose in 3d arary
print(dddarray)
print(dddarray.T)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]
[[[ 0 10 20]
  [ 5 15 25]]

 [[ 1 11 21]
  [ 6 16 26]]

 [[ 2 12 22]
  [ 7 17 27]]

 [[ 3 13 23]
  [ 8 18 28]]

 [[ 4 14 24]
  [ 9 19 29]]]


In [ ]:
#@title reshape

print(vector)
matrix2 = vector.reshape([3, 1])
print(matrix2)

[2. 3. 4.]
[[2.]
 [3.]
 [4.]]


In [ ]:
#@title Flatten
#@markdown This operation also known as `flatten`

vector2 = matrix.reshape([6,])
print(vector2)

[1 2 3 4 5 6]


In [ ]:
vector2 = matrix.flatten() # provide same result
print(vector2)

[1 2 3 4 5 6]


In [ ]:
#@title pad

np.pad(matrix2, (0, 2))

In [ ]:
help(np.pad) # detail usages

Help on function pad in module numpy:

pad(array, pad_width, mode='constant', **kwargs)
    Pad an array.
    
    Parameters
    ----------
    array : array_like of rank N
        The array to pad.
    pad_width : {sequence, array_like, int}
        Number of values padded to the edges of each axis.
        ((before_1, after_1), ... (before_N, after_N)) unique pad widths
        for each axis.
        ((before, after),) yields same before and after pad for each axis.
        (pad,) or int is a shortcut for before = after = pad width for all
        axes.
    mode : str or function, optional
        One of the following string values or a user supplied function.
    
        'constant' (default)
            Pads with a constant value.
        'edge'
            Pads with the edge values of array.
        'linear_ramp'
            Pads with the linear ramp between end_value and the
            array edge value.
        'maximum'
            Pads with the maximum value of all or part of

### Exercise

Please flatten `dddarray` to vector with `reshape` and name is as `vector3`.

## Operations

In [ ]:
print(matrix)
print(matrix2)

[[1 2]
 [3 4]
 [5 6]]
[[2.]
 [3.]
 [4.]]


In [ ]:
matrix2 + matrix # addition

array([[ 3.,  4.],
       [ 6.,  7.],
       [ 9., 10.]])

In [ ]:
matrix2 - matrix # subtraction

array([[ 1.,  0.],
       [ 0., -1.],
       [-1., -2.]])

In [ ]:
matrix2 * matrix # multiplication

array([[ 2.,  4.],
       [ 9., 12.],
       [20., 24.]])

In [ ]:
matrix2 / matrix # division

array([[2.        , 1.        ],
       [1.        , 0.75      ],
       [0.8       , 0.66666667]])

In [ ]:
matrix2 % matrix # modulus

array([[0., 0.],
       [0., 3.],
       [4., 4.]])

In [ ]:
matrix2 ** matrix # exponentiation

array([[2.000e+00, 4.000e+00],
       [2.700e+01, 8.100e+01],
       [1.024e+03, 4.096e+03]])

In [ ]:
matrix2 // matrix # floor division

array([[2., 1.],
       [1., 0.],
       [0., 0.]])

## Aggregation

In [ ]:
print(matrix.max(), matrix.argmax())
print((matrix2 // matrix).max(), (matrix2 // matrix).argmax())

6 5
2.0 0


In [ ]:
print(matrix.min(), matrix.argmin())
print((matrix2 // matrix).min(), (matrix2 // matrix).argmin())

1 0
0.0 3


In [ ]:
matrix.mean() # average

3.5

In [ ]:
matrix.sum()

21

### Exercise: Pad ragged sequence

Please pad `wordmatrix` with empty string `''` to its max length of sublist. Resulting the following word matrix.

```
,-------.-------.-----.
|'Gray' |'wolf' | ''  |
|-------+-------+-----|
|'Quick'|'brown'|'fox'|
|-------+-------+-----|
|'Lazy' |'dog'  | ''  |
`-------^-------^-----'
```

In [ ]:
print(wordmatrix)

[['Gray', 'wolf'], ['Quick', 'brown', 'fox'], ['Lazy', 'dog']]
3
[['Gray' 'wolf' '']
 ['Quick' 'brown' 'fox']
 ['Lazy' 'dog' '']]


# Pandas and seaborn

The main data structures of Pandas are Series(one-dimensional data) and DataFrame(two-dimensional data). These two data structures are sufficient to handle most topical use cases in the fields of finance, statistics, social science, and engineering.

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Series

Series is an object similar to a one-dimensional array, which consists of a set of data (various Numpy data types) and a set of data labels (ie indexes) related to it. Basically, it's a numpy array with index label.

Pandas Series is similar to a column in a table, similar to a one-dimensional array, and can store any data type.
Series is composed of index and columns. The functions are as follows:
pandas.Series( data, index, dtype, name, copy)

You may read the full documentation with:

```python
help(pd.Series)
```

In [ ]:
pd.Series(vector)

0    2.0
1    3.0
2    4.0
dtype: float64


In [ ]:
pd.Series(vector, index = ["x", "y", "z"])

x    2.0
y    3.0
z    4.0
dtype: float64

## DataFrame

![DataFrame](https://url2img-web.herokuapp.com/aHR0cHM6Ly9wYW5kYXMucHlkYXRhLm9yZy9wYW5kYXMtZG9jcy9zdGFibGUvcmVmZXJlbmNlL2FwaS9wYW5kYXMuRGF0YUZyYW1lLmh0bWw=)

DataFrame is a tabular data structure, which contains a set of ordered columns, each column can be a different value type (number, string, Boolean value). DataFrame has both row index and column index. It can be regarded as a dictionary composed of Series (using one index together).

In [ ]:
df = pd.DataFrame(products)

### Viewing data

In [ ]:
df.head()

name  rating  price
0           燕窩鮑魚新年賀歲福袋 | 賀年禮盒 | 送禮     2.0  802.0
1   朱古力及甜點禮盒32粒裝 #Ferrero #金莎 #費列羅     4.0  155.0
2     福星報喜【小品蝴蝶蘭6棵】｜自家蘭花園種植 蘭花 蝴蝶蘭     4.1  880.0
3   尚品虎虎生威鮑魚福袋(1套6款) - 鮑魚盛宴｜送禮自用首選     4.5  679.0
4  風沙鹽焗雞 (約900克/隻 - 急凍熟食 - 翻熱即可食用)     4.3   78.0

In [ ]:
df.head(1)

name  rating  price
0  燕窩鮑魚新年賀歲福袋 | 賀年禮盒 | 送禮     2.0  802.0

In [ ]:
df.tail()

name  rating   price
5                   KQB-29E 迷你韓式光波燒烤爐 香港行貨     4.9  1399.0
6  西藏那曲冬蟲夏草(62-77條/盒)(18.5克/盒) #珍品大條 #送禮推介     4.5  5680.0
7                          皇牌Fango美膚泥漿入門套裝     4.1   896.0
8                   人體工學全網電腦椅辦公椅MR-A810 黑色     5.0  2299.0
9                   [即開即食] 尚品阿福鮑魚(四隻裝) x4罐     4.5   472.0

In [ ]:
df.tail(1)

name  rating  price
9  [即開即食] 尚品阿福鮑魚(四隻裝) x4罐     4.5  472.0

In [ ]:
df.describe()

rating        price
count  10.000000    10.000000
mean    4.190000  1334.000000
std     0.837257  1654.750602
min     2.000000    78.000000
25%     4.100000   523.750000
50%     4.400000   841.000000
75%     4.500000  1273.250000
max     5.000000  5680.000000

In [ ]:
#@title Transpose the data frame
df.describe().T

count     mean          std   min     25%    50%      75%     max
rating   10.0     4.19     0.837257   2.0    4.10    4.4     4.50     5.0
price    10.0  1334.00  1654.750602  78.0  523.75  841.0  1273.25  5680.0

In [ ]:
df.sort_index(axis=0, ascending=False)

name  rating   price
9                   [即開即食] 尚品阿福鮑魚(四隻裝) x4罐     4.5   472.0
8                   人體工學全網電腦椅辦公椅MR-A810 黑色     5.0  2299.0
7                          皇牌Fango美膚泥漿入門套裝     4.1   896.0
6  西藏那曲冬蟲夏草(62-77條/盒)(18.5克/盒) #珍品大條 #送禮推介     4.5  5680.0
5                   KQB-29E 迷你韓式光波燒烤爐 香港行貨     4.9  1399.0
4          風沙鹽焗雞 (約900克/隻 - 急凍熟食 - 翻熱即可食用)     4.3    78.0
3           尚品虎虎生威鮑魚福袋(1套6款) - 鮑魚盛宴｜送禮自用首選     4.5   679.0
2             福星報喜【小品蝴蝶蘭6棵】｜自家蘭花園種植 蘭花 蝴蝶蘭     4.1   880.0
1           朱古力及甜點禮盒32粒裝 #Ferrero #金莎 #費列羅     4.0   155.0
0                   燕窩鮑魚新年賀歲福袋 | 賀年禮盒 | 送禮     2.0   802.0

In [ ]:
df.sort_values(by="rating")

name  rating   price
0                   燕窩鮑魚新年賀歲福袋 | 賀年禮盒 | 送禮     2.0   802.0
1           朱古力及甜點禮盒32粒裝 #Ferrero #金莎 #費列羅     4.0   155.0
2             福星報喜【小品蝴蝶蘭6棵】｜自家蘭花園種植 蘭花 蝴蝶蘭     4.1   880.0
7                          皇牌Fango美膚泥漿入門套裝     4.1   896.0
4          風沙鹽焗雞 (約900克/隻 - 急凍熟食 - 翻熱即可食用)     4.3    78.0
3           尚品虎虎生威鮑魚福袋(1套6款) - 鮑魚盛宴｜送禮自用首選     4.5   679.0
6  西藏那曲冬蟲夏草(62-77條/盒)(18.5克/盒) #珍品大條 #送禮推介     4.5  5680.0
9                   [即開即食] 尚品阿福鮑魚(四隻裝) x4罐     4.5   472.0
5                   KQB-29E 迷你韓式光波燒烤爐 香港行貨     4.9  1399.0
8                   人體工學全網電腦椅辦公椅MR-A810 黑色     5.0  2299.0

In [ ]:
df.sort_values(by="rating")

name  rating   price
0                   燕窩鮑魚新年賀歲福袋 | 賀年禮盒 | 送禮     2.0   802.0
1           朱古力及甜點禮盒32粒裝 #Ferrero #金莎 #費列羅     4.0   155.0
2             福星報喜【小品蝴蝶蘭6棵】｜自家蘭花園種植 蘭花 蝴蝶蘭     4.1   880.0
7                          皇牌Fango美膚泥漿入門套裝     4.1   896.0
4          風沙鹽焗雞 (約900克/隻 - 急凍熟食 - 翻熱即可食用)     4.3    78.0
3           尚品虎虎生威鮑魚福袋(1套6款) - 鮑魚盛宴｜送禮自用首選     4.5   679.0
6  西藏那曲冬蟲夏草(62-77條/盒)(18.5克/盒) #珍品大條 #送禮推介     4.5  5680.0
9                   [即開即食] 尚品阿福鮑魚(四隻裝) x4罐     4.5   472.0
5                   KQB-29E 迷你韓式光波燒烤爐 香港行貨     4.9  1399.0
8                   人體工學全網電腦椅辦公椅MR-A810 黑色     5.0  2299.0

## Selection

In [ ]:
#@title Select by column index
df['rating']

0    2.0
1    4.0
2    4.1
3    4.5
4    4.3
5    4.9
6    4.5
7    4.1
8    5.0
9    4.5
Name: rating, dtype: float64

In [ ]:
#@title Select by row index
df.loc[0]

name      燕窩鮑魚新年賀歲福袋 | 賀年禮盒 | 送禮
rating                         2
price                        802
Name: 0, dtype: object

In [ ]:
#@title Select by row and column index
df.loc[0:4,'rating']

0    2.0
1    4.0
2    4.1
3    4.5
4    4.3
Name: rating, dtype: float64

In [ ]:
#@title Select by row position
df.iloc[3]

name      尚品虎虎生威鮑魚福袋(1套6款) - 鮑魚盛宴｜送禮自用首選
rating                               4.5
price                                679
Name: 3, dtype: object

In [ ]:
#@title Select by row and column position
df.iloc[0:3, 0:2]

name  rating
0          燕窩鮑魚新年賀歲福袋 | 賀年禮盒 | 送禮     2.0
1  朱古力及甜點禮盒32粒裝 #Ferrero #金莎 #費列羅     4.0
2    福星報喜【小品蝴蝶蘭6棵】｜自家蘭花園種植 蘭花 蝴蝶蘭     4.1

In [ ]:
#@title select by condition
df[df['rating'] < 4]

name  rating  price
0  燕窩鮑魚新年賀歲福袋 | 賀年禮盒 | 送禮     2.0  802.0

In [ ]:
#@title select values with condition
df[df[['price','rating']] > 2]

name  rating   price
0  NaN     NaN   802.0
1  NaN     4.0   155.0
2  NaN     4.1   880.0
3  NaN     4.5   679.0
4  NaN     4.3    78.0
5  NaN     4.9  1399.0
6  NaN     4.5  5680.0
7  NaN     4.1   896.0
8  NaN     5.0  2299.0
9  NaN     4.5   472.0

## Setting values in `DataFrame`

In [ ]:
#@title create new column in DataFrame with label `price_mean` and setting the mean value of price to it.
df.at[:, 'price_mean'] = df['price'].mean()
df.head()

name  rating  price  pricemean  price_mean
0           燕窩鮑魚新年賀歲福袋 | 賀年禮盒 | 送禮     2.0  802.0     1334.0      1334.0
1   朱古力及甜點禮盒32粒裝 #Ferrero #金莎 #費列羅     4.0  155.0     1334.0      1334.0
2     福星報喜【小品蝴蝶蘭6棵】｜自家蘭花園種植 蘭花 蝴蝶蘭     4.1  880.0     1334.0      1334.0
3   尚品虎虎生威鮑魚福袋(1套6款) - 鮑魚盛宴｜送禮自用首選     4.5  679.0     1334.0      1334.0
4  風沙鹽焗雞 (約900克/隻 - 急凍熟食 - 翻熱即可食用)     4.3   78.0     1334.0      1334.0

In [ ]:
#@title setting value in DataFrame by position
df.iat[0, 1] = 0
df.head()

name  rating  price  pricemean  price_mean
0           燕窩鮑魚新年賀歲福袋 | 賀年禮盒 | 送禮     0.0  802.0     1334.0      1334.0
1   朱古力及甜點禮盒32粒裝 #Ferrero #金莎 #費列羅     4.0  155.0     1334.0      1334.0
2     福星報喜【小品蝴蝶蘭6棵】｜自家蘭花園種植 蘭花 蝴蝶蘭     4.1  880.0     1334.0      1334.0
3   尚品虎虎生威鮑魚福袋(1套6款) - 鮑魚盛宴｜送禮自用首選     4.5  679.0     1334.0      1334.0
4  風沙鹽焗雞 (約900克/隻 - 急凍熟食 - 翻熱即可食用)     4.3   78.0     1334.0      1334.0

## Export and Import DataFrame to/from file

In [ ]:
#@title export to csv file
df.to_csv('products.csv')

In [ ]:
#@title export to excel file
df.to_excel('products.xlsx')

In [ ]:
#@title export to json file
df.to_json('product_data.json')

In [ ]:
#@title import from csv file
csvdf = pd.read_csv('products.csv')
csvdf.head()

Unnamed: 0                             name  ...  pricemean  price_mean
0           0           燕窩鮑魚新年賀歲福袋 | 賀年禮盒 | 送禮  ...     1334.0      1334.0
1           1   朱古力及甜點禮盒32粒裝 #Ferrero #金莎 #費列羅  ...     1334.0      1334.0
2           2     福星報喜【小品蝴蝶蘭6棵】｜自家蘭花園種植 蘭花 蝴蝶蘭  ...     1334.0      1334.0
3           3   尚品虎虎生威鮑魚福袋(1套6款) - 鮑魚盛宴｜送禮自用首選  ...     1334.0      1334.0
4           4  風沙鹽焗雞 (約900克/隻 - 急凍熟食 - 翻熱即可食用)  ...     1334.0      1334.0

[5 rows x 6 columns]

In [ ]:
#@title import from excel file
exceldf = pd.read_excel('products.xlsx')
exceldf.head()

Unnamed: 0                             name  ...  pricemean  price_mean
0           0           燕窩鮑魚新年賀歲福袋 | 賀年禮盒 | 送禮  ...       1334        1334
1           1   朱古力及甜點禮盒32粒裝 #Ferrero #金莎 #費列羅  ...       1334        1334
2           2     福星報喜【小品蝴蝶蘭6棵】｜自家蘭花園種植 蘭花 蝴蝶蘭  ...       1334        1334
3           3   尚品虎虎生威鮑魚福袋(1套6款) - 鮑魚盛宴｜送禮自用首選  ...       1334        1334
4           4  風沙鹽焗雞 (約900克/隻 - 急凍熟食 - 翻熱即可食用)  ...       1334        1334

[5 rows x 6 columns]

In [ ]:
#@title import from json file
jsondf = pd.read_json('products.json')
jsondf.head()

code  ... numberOfColors
0  H5938001_S_NYC-GB-202001  ...            NaN
1       H0888001_S_10140820  ...            NaN
2        H6416001_S_GF00024  ...            NaN
3          H0817001_S_11375  ...            NaN
4        H8640001_S_1002551  ...            NaN

[5 rows x 65 columns]